name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run weekly to catch any grammar updates
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build-matrix:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
            build-cmd: cd tree-sitter-native && make
          - os: macos-latest
            rid: osx
            build-cmd: ./build-macos-universal.sh
          - os: windows-latest
            rid: win-x64
            build-cmd: msbuild tree-sitter-native/tree-sitter-native.sln /p:Configuration=Release /p:Platform=x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential nodejs npm
        sudo npm install -g tree-sitter-cli

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install tree-sitter
        chmod +x build-macos-universal.sh

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        npm install -g tree-sitter-cli
        choco install make

    - name: Update grammar sources
      shell: bash
      run: |
        chmod +x update-grammars.sh
        ./update-grammars.sh

    - name: Build native libraries
      shell: bash
      run: ${{ matrix.build-cmd }}

    - name: Build .NET project
      run: |
        cd src
        dotnet build TreeSitter.csproj --configuration Release

    - name: Run tests
      run: |
        dotnet test tests/TreeSitter.Tests.csproj --configuration Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: native-libraries-${{ matrix.rid }}
        path: build/runtimes/${{ matrix.rid }}/native/
